### ISSUE TITLE
apple app store submission warning regarding UIWebView

### ISSUE THREAD

**Issue by oscargoldman** [flurry/unity-flurry-sdk#11] opened 2020-03-10 19:06 UTC
We're using the unity flurry sdk and we just started getting warnings that our app won't be approved after december 2020 due to depricated API.

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs starting from December 2020 . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

User grep in our xcode folder indicates this SDK implements UIWebView. Any plans to remove it before December?

**Comment by flurrydev** [comment] 2020-03-10 20:44
Hello,

The issue is resolved in our most recent releases. Please update to the latest package 2.4.0, and make sure you remove the older files.

**Comment by poting-oath** [comment] 2020-08-27 16:15
Fixed in 2.4.0 release.

**Closed by poting-oath** 2020-08-27 16:15 UTC
